name: Update README with Lichess Bot Ratings

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch: # Allows you to trigger manually from the Actions tab

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Fetch Lichess Bot Ratings
      id: fetch_ratings
      run: |
        BOT_USERNAME="silkfish"
        RAPID_RATING=$(curl -s "https://lichess.org/api/user/${BOT_USERNAME}" | jq '.perfs.rapid.rating')
        CLASSICAL_RATING=$(curl -s "https://lichess.org/api/user/${BOT_USERNAME}" | jq '.perfs.classical.rating')
        echo "rapid_rating=${RAPID_RATING}" >> $GITHUB_ENV
        echo "classical_rating=${CLASSICAL_RATING}" >> $GITHUB_ENV

    - name: Update README
      run: |
        sed -i "s/Rapid_Rating-[0-9]*/Rapid_Rating-${{ env.rapid_rating }}/" README.md
        sed -i "s/Classical_Rating-[0-9]*/Classical_Rating-${{ env.classical_rating }}/" README.md

    - name: Commit changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "GitHub Actions"
        git add README.md
        git commit -m "Update Lichess bot ratings"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
